#!/usr/bin/env bash
# create file and terminates itself when receiving a SIGQUIT or SIGTERM signal

closer()
{
rm /var/run/myscript.pid
exit
}

echo "$$" > /var/run/myscript.pid

while ((1))
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && closer' SIGTERM
  trap 'closer' SIGQUIT
done
