#!/usr/bin/env bash
# display displays numbers from 1 to 100 switch to message for 3, 5, 15

i=1
for (( i = 1; i <=100; i++))
do
if (( i % 3 == 0 && i % 5 == 0 ))
then
echo "FizzBuzz"
elif (( i % 3 == 0 ))
then
echo "Fizz"
elif (( i % 5 == 0 ))
then
echo "Buzz"
else
echo "$i"
fi
done
