#!/usr/bin/env bash
# This script is displaying "Best School" 10 times "bad luck" at 4th time and "good luck" at 8th time

i=1
while [ $i -le 10 ]
do

if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
 fi

(( i++ ))

done
